#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install chaincode
  hosts: localhost
  vars_files:
    - common-vars.yml
    - org2-vars/org2-vars.yml
    - org2-vars/vault
  tasks:
    - name: Install the chaincode on the peer
      ibm.blockchain_platform.installed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ org2_peer_name }}{{ item}}"
        identity: "{{ org2_name }} Admin.json"
        msp_id: "{{ org2_msp_id }}"
        path: "{{ smart_contract_package }}"
      loop: "{{(range(1, peers + 1, 1)) | list }}"
      when: peers > 1

    - name: Install the chaincode on the peer
      ibm.blockchain_platform.installed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ org2_peer_name }}"
        identity: "{{ org2_name }} Admin.json"
        msp_id: "{{ org2_msp_id }}"
        path: "{{ smart_contract_package }}"
      when: peers == 1
